### ISSUE TITLE
Can’t reorder MapInfo entries

### ISSUE THREAD

**Issue by rohkea** [20kdc/gabien-app-r48#1]
I’m using an outdated versions (demetr48.jar and v0.6-4-B), I still haven’t tried compiling R48 myself. So, this bug might not be present in the latest version. I’ve only tested this in R2K\[3?\], not in the other engines.

When I assign a parent of the map, I get ‘Parent Inconsistency Warning’.

![inconsistency](https://user-images.githubusercontent.com/3201243/28743202-9f869c98-744c-11e7-81ff-8d6900af9e49.png)

Steps to reproduce:

* Run R48 in an empty root folder,
* (On the screenshot, I’ve renamed the first map into Real World)
* Add the second map (in the screenshot, I’ve named it Dream World), move it out,
* Add the third map (in the screenshot, it’s named Myanmar), try setting its parent ID to 1 to make it a sub-map of the First map (aka Real World).

**Expected result:** the third map (‘Myanmar’) should appear below the first map (‘Real world’).

**Current result:** a warning ‘Information: Parent Inconsistency Warning 3 o 3’ appears. I can only see Myanmar🇲🇲 in the dream world 😿

**Comment by 20kdc** [comment]
The ability to manually change parent\_id without at least a warning was indeed a bug, because that lead to inconsistencies...
I've changed the ">>" to "Parent Here", and made the relevant fields read-only.
It's easy to reverse if someone has to manually edit those fields.
