### ISSUE TITLE
Setting tile as ‘impassable’ requires 4 mouse clicks

### ISSUE THREAD

**Issue by rohkea** [20kdc/gabien-app-r48#10]
One common scenario for editing tileset data is setting the passability to ‘impassable’. Most tiles don’t require directional passability: if it’s a rock or a bush, I can’t enter it from any side. So, in RM2k\[3\], there are two modes: for setting normal passability and for setting directional passability.

But R48 forces me to click on all the directions just to set the rock impassable.

So, R48 workflow to set a few tiles as impassable is:

* Hover the mouse over the tile to change,
* Click on it,
* Hover the mouse over the flags to the right,
* Click on 1:down,
* Click on 2:left,
* Click on 3:right,
* Click on 4:up.

The RM2k\[3\] behaviour is:

* (Few mouse movements are neccessary because the mouse doesn’t travel away from the tile list)
* Click on the tile.

It would be nice if this was simplified in R48. Possible solutions I can think of:

* Add some action like right/middle-clicking on the tile that would toggle the 1+2+3+4 flags of that tile (and won’t require moving the mouse from the tile list).
* Add a button to set/unset all 1:down, 2:left, 3:right, 4:up with one click — this would reduce the number of clicks to just 2 (1 to set the tile, 1 to change the passability — still more actions then RM2k’s 1 click, though).
* Maybe something else?

**Comment by 20kdc** [comment]
...GitHub deciding it should close issues before the solution is actually double-checked again *sigh*
