### ISSUE TITLE
Clicking with LMB and RMB at the same time makes window unresponsible

### ISSUE THREAD

**Issue by rohkea** [20kdc/gabien-app-r48#14]
Clicking 2 buttons at the same time makes window unresponsive

- Open any sub-window,
- Click both left and right mouse button at the same time.

Result: Window can’t be moved, closed, interacted with, etc.

This was true with yesterday’s build, I can’t test with today’s build because of #13

**Comment by 20kdc** [comment]
Is this fixed yet?

**Comment by rohkea** [comment]
Yes, the problem doesn’t happen anymore, thanks!

**Comment by 20kdc** [comment]
Closed as user reports solved.
