### ISSUE TITLE
Tileset’s @highpass_data doesn’t need `upper` set by default

### ISSUE THREAD

**Issue by rohkea** [20kdc/gabien-app-r48#15]
The `upper` flag shows that the item should be above the player. Most L2 tiles don’t need this.

Here’s how the default Basis/World `@highpass_data` looks:
![r48-default-upper](https://user-images.githubusercontent.com/3201243/29239187-c93622c0-7f50-11e7-8aee-f352db692a63.png)

As you can see, the overwhelming majority of tiles don’t have `upper`. R48 sets this by default, meaning most tiles need to be customized. It would be more useful if the tiles in `@highpass_data` didn’t have the `upper` flag.

**Comment by 20kdc** [comment]
...whoops. I assumed having upper set by default was more intuitive (lower layer has lower tiles, upper layer has upper tiles)...
