### ISSUE TITLE
2017-09-14 R2k3 update stuff

### ISSUE THREAD

**Issue by 20kdc** [20kdc/gabien-app-r48#18]
So David Cherry (@CherryDT, github-please-dont-ping) updated 2k3.
And added stuff.
LOTS of stuff.
Cherry lists the changes below (at least I assume this is written by Cherry):
https://docs.google.com/document/d/1sXlXZIXdjxVq5gh_lPFuFLMbMRzZe4BKPpRI13ZD2Qc/edit

Need to canonize PPP, deal with spritesheet stuff... etcetc
Waiting on EasyRPG TestGame devs for this as I have no copy of 2k3, and don't want one for legal reasons.
Cherry, if you're reading this... well done. The ball is in my court. 😄

**Comment by CherryDT** [comment]
What is github-please-dont-ping? Because I did get a notification (if that's what it was supposed to prevent)

**Comment by 20kdc** [comment]
...list of things to do, figure out how to mention a GitHub username *without* pinging. Flip.

**Comment by Ghabry** [comment]
Created an issue in the testgame repo https://github.com/EasyRPG/TestGame/issues/35

And lets wait for some real games using this, by now I only know Cherrys PKMN demo from a video and afaik this is not public.

**Comment by 20kdc** [comment]
Would agree if this was EasyRPG Player, but this is R48. Full editing support is a goal here.

**Comment by CherryDT** [comment]
@Ghabry Archeia says that she will soon publish her "demo game" she made for the update.

**Comment by 20kdc** [comment]
Everything appears to be in order with v0.7.1, when the demo game is available, if I'm notified I'll inspect it to check that everything regarding 1.12 editing support is working.
