### ISSUE TITLE
Entering negative numbers is non-optimal

### ISSUE THREAD

**Issue by rohkea** [20kdc/gabien-app-r48#19]
Entering negative numbers is cumbersome. ‘-’ is converted into ‘0’, so you need to type a positive number, press ‘Home’ and add a minus sign at the beginning.

**Comment by 20kdc** [comment]
Yeah, this definitely needs fixing, though it's actually a UINumberBox issue (gabien-common)

**Comment by 20kdc** [comment]
Fixed with https://github.com/20kdc/gabien-common/commit/294e99498f6e65e01a83672b971fe6575f13abc6 , I think (ping me on IRC if this isn't the right way to do this)
