### ISSUE TITLE
(20kdc note: Support For Battle2 For [see later issue comments]) Visual Battle Animation editor for R2K[3?]

### ISSUE THREAD

**Issue by rohkea** [20kdc/gabien-app-r48#2]
RPG Maker 2000/2003 allows editing animations visually, by dragging the sprites around with mouse. This makes editing animations much more intuitive.

This is a big feature but I think some code already exists for it for the RXP engine?

**Comment by 20kdc** [comment]
Working on even more refactoring of the relevant code for this. Basically I'm making the XP/VXA animation editor's use of tables the exception, not the rule.

**Comment by 20kdc** [comment]
Oh, right, this is mostly done apart from Battle2 - which is on hold until I can find something that uses it to check against.

**Comment by 20kdc** [comment]
Likely fixed with the latest push.
