### ISSUE TITLE
Mouse wheel scrolls way too much in the Scripts list in VXA

### ISSUE THREAD

**Issue by rohkea** [20kdc/gabien-app-r48#21]
I  still need to comment on the other issue, but I promised someone else to help them with scripts, and I’ve noticed a little annoying behaviour: the mouse wheel scrolls over some items.

Before scrolling:
![before-scrolling](https://user-images.githubusercontent.com/3201243/31911650-0b0b8690-b84a-11e7-9fe7-6804fa030729.png)

After scrolling:
![after-scrolling](https://user-images.githubusercontent.com/3201243/31911665-14089972-b84a-11e7-8c6c-dc36fed135c4.png)

As you can see, scripts 60, 61, 62, 63, 64, 65, 66 are unreachable when using a mouse wheel.

**Comment by 20kdc** [comment]
Fixed as of https://github.com/20kdc/gabien-common/commit/6c8829dad08685d761142ddb043136a97efab603 - which fixes these issues across the application.

**Comment by 20kdc** [comment]
Re-opening because I just realized the current values may or may not still need calibration.

**Comment by rohkea** [comment]
Thanks! Works well for me, both for XP and VXA.

**Comment by 20kdc** [comment]
By the sound of it, they don't need calibration, so closing.
