### ISSUE TITLE
Adding a script without importing it makes game unrunnable

### ISSUE THREAD

**Issue by rohkea** [20kdc/gabien-app-r48#23]
Steps to reproduce:

1. Open a VXA game in R48.
2. Open Database Objects → Scripts
3. Add a new script at any position
4. Run the game.

**Expected result:** no changes should be visible when running the game, since a newly-added script should be just an empty script with no code and shouldn’t affect anything.

**Actual result:** an error occurs (unless I export the empty script and re-import it):
![‘Failed to load script’ error message.](https://user-images.githubusercontent.com/3201243/31966481-8423e562-b913-11e7-8570-6867052b0da8.png)

**Comment by 20kdc** [comment]
I think I know why this is, but now I need to get an empty zlib stream...

**Comment by 20kdc** [comment]
I don't know if that's actually accepted by RGSS, so testing needed.

**Comment by rohkea** [comment]
Thanks! Tested in both RXP and RVXA engines, works well.
