### ISSUE TITLE
Can’t edit party members in RXP

### ISSUE THREAD

**Issue by rohkea** [20kdc/gabien-app-r48#24]
I’ve tried editing `System/@party_members` and this is what I saw:
![cant-edit-xp-party-members](https://user-images.githubusercontent.com/3201243/32074695-f25cf740-baa2-11e7-9a83-9b8479c1e436.png)

When I click on the party member (she exists in the Actors, btw), I get the following window:
![trying-to-edit-xp-party-members](https://user-images.githubusercontent.com/3201243/32074718-059cd1f4-baa3-11e7-8c7c-3bd4e3473cb3.png)

When I click ‘Add @ 1’, I get ‘Can’t edit: null’. Clicking on it brings the same window.

This only affects RXP, while RVXA and R2k\[3] work well.

**Comment by 20kdc** [comment]
Hopefully fixed with https://github.com/20kdc/gabien-app-r48/commit/4b64c851350cfdf88f85e608fd864341931bc98a

**Comment by rohkea** [comment]
This works now, thanks!
