### ISSUE TITLE
Feature request: unify minimap with zoom

### ISSUE THREAD

**Issue by rohkea** [20kdc/gabien-app-r48#26]
R48 has a minimap mode, which is a handy way of working with large maps. It would be nice if it could be unified with the zoom-in function into a single zoom function that zooms both in and out.

The minimap is currently handled differently from zoom. Zoom only zooms in, with arbitrary sizes, while minimap only zooms out, at a pre-set size (but allowing you to zoom it in; the zoomed-in minimap is not same as normal tiles).

I think it makes sense to unify these because:

* Zoom-out would be easier to find. Zoom function is more prominent, while Minimap is only available through the keyboard.
* It would allow changing the minimap scale. The current minimap scale is too big. If I move the map in the minimap mode, I find it difficult to understand where I’ll und up after closing the minimap, because the scale is too big.

**Comment by 20kdc** [comment]
Good news: This is almost ready, just need to try and get the mul/div parameters right...

**Comment by 20kdc** [comment]
Note: This may or may not cause some undiagnosed tile rendering issues, particularly of the kind where specific groups of tiles that haven't been checked start rendering completely wrongly. It will be quite obvious if / when these occur, though.

**Comment by rohkea** [comment]
Thanks! Works great in the XP and VX Ace modes.

Unfortunately, in the RM2k\[3\] mode, the non-animated autotiles are replaced with animated ones:

![rm2k-autotiles](https://user-images.githubusercontent.com/3201243/32447185-5f3cf5dc-c31c-11e7-86b8-f114d898bb72.png)

**Comment by 20kdc** [comment]
Whoops. Accidentally forgot the x tileSize calculations for those ATs. I was trying to deal with ETS and prepare for any possible EasyRPG 2x support at once, and that didn't go well.

**Comment by 20kdc** [comment]
Status on this? I think I fixed it after that last comment, but need more information.

**Comment by 20kdc** [comment]
Assuming fixed given my own testing - reopen if I still screwed up somehow
