### ISSUE TITLE
Cannot reorganize windows once undocked and redocked

### ISSUE THREAD

**Issue by Tom-III** [20kdc/gabien-app-r48#29]
If you un dock the map info tab into a window and then re minimize it it will go to the end of the queue and not its original position without the ability to reorganize it

**Comment by 20kdc** [comment]
Should be done now. Thoughts?

**Comment by 20kdc** [comment]
Demetrius confirmed on EasyRPG IRC that everything was AOK with this resolution, closing for v1.0
