### ISSUE TITLE
Can’t set root path :(

### ISSUE THREAD

**Issue by rohkea** [20kdc/gabien-app-r48#3]
I’ve tried setting Root path with the latest version (did `gradle jar` in all repos and `gradle run`) and still can’t do it, the DB is not loaded.

https://github.com/20kdc/gabien-app-r48/commit/302db938fc679f756cc803c0b8c51b0d77de676d didn’t seem to have helped.

**Comment by rohkea** [comment]
Works now, thanks!

**Comment by 20kdc** [comment]
...Github, no automatically closing just based on what I say in commits! I said *probably*!
...well, whatever. It worked.
