### ISSUE TITLE
XP: invalid @pages[N]@graphic@blend_type value -1

### ISSUE THREAD

**Issue by rohkea** [20kdc/gabien-app-r48#32]
When creating an event in the XP mode, its ``@pages[N]@graphic@blend_type`` is set to the default value of -1 : "KeepDestAlpha"

If you try to create an event with such ``@blend_type``, you’ll get an error:

![An error with the text: ‘Script ‘Sprite_Character’ line 68: ArgumentError occured. bad value for blend_type’.](https://user-images.githubusercontent.com/3201243/42519967-d059b7e2-846d-11e8-8e78-b6547f69a54e.png)

Probably this value should be deleted (unless you’re planning to support it in your custom pancake-based scripts for mkxp?), and `0 : "Normal"` should be used as the default one.

**Comment by 20kdc** [comment]
It's probably mkxp-only or something - that's where I got the values from

**Comment by rohkea** [comment]
Maybe it would need an _mkxp suffix or something, then?

**Comment by 20kdc** [comment]
This should be resolved now. Status?

**Comment by rohkea** [comment]
Yes, it’s resolved.
