### ISSUE TITLE
Unhelpful defaults for adding/removing items

### ISSUE THREAD

**Issue by rohkea** [20kdc/gabien-app-r48#33]
The commands for modifying items, weapons, armour have the default value of ‘0’ for their argument.

Maybe it’s possible to use ‘1’ as the default value when creating such commands? Giving/removing zero items makes the command no-op, while giving one item is a very common use-case.

**Comment by 20kdc** [comment]
Took me a while to get around to this - which commands in particular?

**Comment by 20kdc** [comment]
...I've gone and added a lot of default values, but I'm unsure if these were the ones you wanted.

**Comment by rohkea** [comment]
Thanks! This works great now. Some other commands that might benefit from this could be:

* RXP’s 127 Modify Weapon
* RXP’s 128 Modify Armour

**Comment by 20kdc** [comment]
In theory they already should benefit from it, but I'm guessing the command creation code is having an off day today

**Comment by rohkea** [comment]
Yes, it works, thanks!

**Comment by 20kdc** [comment]
Closing - reopen if there's anything to add.
