### ISSUE TITLE
Single water tile has invalid ID

### ISSUE THREAD

**Issue by rohkea** [20kdc/gabien-app-r48#34]
If you place a single water autotile around the non-water tiles in R48, this triggers an error in EasyRPG Player:

> Warning: Invalid AB autotile ID: 47 (a_subtile = 47)

Also, the autotile is displayed incorrectly in both EasyRPG Player and RPG_RT (look at the tile to the right of the top house):

![Wrong autotile: a water without transitions is displayed in RPG_RT](https://user-images.githubusercontent.com/3201243/46111201-c5d13700-c1ee-11e8-9df4-e06e1b3cd565.png)

Here’s how R48 shows this map:

![The same map is shown in R48, with transitions](https://user-images.githubusercontent.com/3201243/46111218-daadca80-c1ee-11e8-9e28-f1e281ff05f7.png)

The problem only happens for animated autotiles, not for regular autotiles.

**Comment by 20kdc** [comment]
...try now?

**Comment by rohkea** [comment]
Works fine now, thanks!
