### ISSUE TITLE
Pixel-perfect zoom mode?

### ISSUE THREAD

**Issue by rohkea** [20kdc/gabien-app-r48#36]
I really miss the old zoom mode that only chose pixel-perfect zooms (1x, 2x, etc.). The current zoom mode is more flexible, but it takes me more time to find a zoom mode where all pixels have the same size. When making maps, I usually only use these zooms: 100%, 200%, 300%, etc, because I know an ‘underlying’ pixel corresponds to one ‘screen’ pixel.

Most zooms R48 offers mean that pixels have different sizes. Here’s an illustration:
![pixels-](https://user-images.githubusercontent.com/3201243/46249444-01a80e80-c432-11e8-9331-6782c91c7487.png)

Red lines are borders of ‘real’ pixels, blue lines subdivide zoomed pixels. Most R48 zooms now make pixels unequal (on the image, some pixels are 3px while others are 2px). These zoom modes make it harder to judge about how the map will look in the end.

Current zoom mode works like RPG Maker MV, but:

* MV has an ‘100% zoom’ buttom (‘1:1’ icon) which reverts to the default zoom, which is pixel-perfect,
* MV tiles are larger (48x48) so you rarely need 2x and larger zooms, most time you need 100% zoom (but in RM2k\[3]/EasyRPG games, you work with larger zooms most of the time, because 16x16 us just too small — in fact, RM2k treats 200% zoom as the default one, not 100%).

Some function to use only pixel-perfect zooms would be welcome. Maybe a switch somewhere, or ‘if you hold shift key, only zooms with integer number of pixels are chosen’, or something along these lines. Or maybe a ‘revert to 100% zoom’ like in RPG Makers (although ‘revert to 200%’ would probably be more appropriate for 2k\[3\] mode).

**Comment by 20kdc** [comment]
This mode was already bound to Shift, but now it's also bound to Control. Just in case.
And yes, I did run out of room for more informative controls text...

**Comment by rohkea** [comment]
Thanks!
