### ISSUE TITLE
Move routes of RM2000 don’t work in EasyRPG Player (unlike ones created in RM2000)

### ISSUE THREAD

**Issue by rohkea** [20kdc/gabien-app-r48#37]
R48 editor creates move routes that only work in RPG_RT, but not in EasyRPG Player.

Here’s a test game: 
[TestMoveCommands.zip](https://github.com/20kdc/gabien-app-r48/files/2435188/TestMoveCommands.zip)
The left character has a move route created by RPG Maker 2000, right character has a move route created by R48. In RPG_RT, both work. In Player, the last command of the second route is ignored.

**Comment by Ghabry** [comment]
The problem is that the frequency value is not saved and set to "0".

https://github.com/EasyRPG/Player/pull/1427/commits/0390b9ad1ebedc1805e7309d1c90acb6c9da92af

**Comment by 20kdc** [comment]
I'm confused. Is it *not saved* or was it never set in the first place?
If it wasn't set, then it's a usability error but not a critical bug.
If it's not saved, then it's a critical IO bug.

**Comment by Ghabry** [comment]
Well is an event argument, so is saved but as 0. CC @rohkea

**Comment by rohkea** [comment]
Thanks! It was indeed a usability bug, I never changed the value in RM2k and I didn’t know I needed to change it.

Please use 6 and not 3 as the default value. Using slower default values mean the character will stop to think before taking each step, which is less useful than making the character actually do what you asked.

**Comment by 20kdc** [comment]
Ok, there's now a global place for the default values (frequency 6, speed 3) which is in use.

**Comment by 20kdc** [comment]
Given the thumbs-up, assuming fixed. Re-open if not the case.
