### ISSUE TITLE
Undo button doesn’t appear when it should

### ISSUE THREAD

**Issue by rohkea** [20kdc/gabien-app-r48#38]
When I open a program and make an action, Undo button is not visible. Looks like I need to change the size of the R48 window to make ‘Undo’ appear.

Also, clicking on Undo makes it disappear:
![An example of R48 image editor with something drawn, but no Undo button.](https://user-images.githubusercontent.com/3201243/46598268-3da33980-caec-11e8-9585-de9c87955a49.png)

Also, why hide it at all? Those re-emerging buttons make it harder to learn where I should click, because buttons change their positions and I need to search for the new button position each time. Different panel size for different tools is questionable but at least understandable (only rows are added/removed and only when you switch tools), but the logics behind hiding buttons is hard to get used to.

**Comment by 20kdc** [comment]
The buttons shouldn't be getting hidden at all. They are supposed to rearrange themselves according to screen size, but they aren't supposed to disappear. Will investigate.

**Comment by rohkea** [comment]
The problem doesn’t occur anymore, thanks!
