### ISSUE TITLE
Floodfill and line tool for image editor?

### ISSUE THREAD

**Issue by rohkea** [20kdc/gabien-app-r48#39]
R48 image editor really shines when drawing smaller pixel-art tiles (the TileView is totally rad), but drawing larger images is quite challenging. I’m drawing monsters now, and I miss some way to quickly colour larger areas. (And I haven’t even gotten around to the battle backdrop, which is even larger.)

The usual way to make editing larger areas easier is a floodfill tool (and a line tool could help drawing the borders for larger areas — although that’s less important than floodfill, IMHO).

If it were possible to add FloodFill and Line tool to the image editor, I think it would help with drawing larger images.

**Comment by 20kdc** [comment]
In-progress now, but I want to add a few features to the fill tool before I say it's done.

**Comment by 20kdc** [comment]
This should do it.

**Comment by rohkea** [comment]
This works great with palettised images, thanks!

However, in 32-bit ARGB images, it seems to fill everything with transparency.

**Comment by 20kdc** [comment]
Apparently I can't read the manual on my own stuff. Fixing now.

**Comment by 20kdc** [comment]
...and apparently I needed to make another quick fix because of... ok, I think basic stuff should work again now

**Comment by 20kdc** [comment]
Closing as it sounds like it's done.
