### ISSUE TITLE
Map tile preview is misleading on Android

### ISSUE THREAD

**Issue by rohkea** [20kdc/gabien-app-r48#41]
On Android, map tile preview is triggered by click, so it’s not really a preview. However, it does show up. This is confusing in two cases:

* After placing the autotile, the preview displays the ‘main’ autotile instead of the configuration that was really placed. This makes it hard to understand how the map really looks.
* In camera mode, the click on a map shows the object, making it seem that the object was placed. It makes it hard to understand that you’re in the camera mode.

I suggest either:

* disabling the preview by click (only show it after the mouse move that was triggered by a real mouse move and not by click), or
* disabling the preview on Android.

The first option might be better for touch-screen laptops.

**Comment by 20kdc** [comment]
Update: Preview is completely disabled for most tools on Android. The only tool that *needed* it - block paste - has been modified accordingly.

**Comment by 20kdc** [comment]
...Assuming this is fixed since... I *think* you haven't brought up any further issues with it? Re-open if I'm incorrect.
