### ISSUE TITLE
Pinch-to-zoom on Android would be nice

### ISSUE THREAD

**Issue by rohkea** [20kdc/gabien-app-r48#43]
Pinch-to-zoom is a common gesture when you place two fingers on screen and then increase the distance between them (to zoom in) or decrease it (to zoom out). When zooming in, the location of fingers determines the area to be zoomed in. (And while doing that, you can still scroll the view area by moving the fingers without changing the distance between them.)

It’s not really required but almost any Android application supports them, so it makes sense to add them. In fact, even I tried using them without realising R48 doesn’t have this.

**Comment by 20kdc** [comment]
Time I upgrade the mobile emulation system to allow debugging multitouch gestures, I guess.
I've been keeping away from multitouch-specific code for that reason.

**Comment by 20kdc** [comment]
It's now implemented. I'll test it here, but you should test too in case I screwed up some non-obvious usability stuff

**Comment by 20kdc** [comment]
Here's the build I'll be testing with. 
[v1.3-a.apk.zip](https://github.com/20kdc/gabien-app-r48/files/2593328/v1.3-a.apk.zip)
This uses AVC 14, so I hope I remember this later or you might have issues updating from this.

**Comment by 20kdc** [comment]
You noted 'Dragging and zooming works great' over Discord, so I'm assuming this is resolved ; Re-open if I'm incorrect about this...
