### ISSUE TITLE
Scrolling by dragging and flinging on Android might be nice

### ISSUE THREAD

**Issue by rohkea** [20kdc/gabien-app-r48#44]
On Android, there is no mouse wheel, so scrolling is less comfortable than on desktop.

It might make sense to implement the [default Android behaviour](https://developer.android.com/training/gestures/scroll) for scrolling:

* slowly dragging most dialogs boxes scrolls them,
* quick drag action initiates the fast scroll; the scroll speed is determined by the speed of the initial drag, and decreases over time; the scroll can be stopped by another drag.

I don’t know if these are useful only on Android, I think desktop PCs with touchscreens could benefit from them as well.

**Comment by 20kdc** [comment]
This'll probably mess up the implementation of any drag-based element that could end up in the UI tree, unfortunately, but this might be reasonable to implement on scrollbars.

**Comment by Leo40Git** [comment]
Most Android apps use long taps to activate dragging things.

**Comment by rohkea** [comment]
> Most Android apps use long taps to activate dragging things.

I think that’s for dragging one thing, right? (So basically it’s a selection. I’ve seen it used for opening menus, too, e.g. in Discord app and Orgzly.)

I was talking about dragging the whole contents to scroll it, not about dragging a single element. (I don’t think R48 has any single elements to drag anyway?)

**Comment by 20kdc** [comment]
Last I checked, long taps (more like holds really) activate selection/action stuff, while this refers to the "swipe up to quickly go down a list with 'momentum'" vs. "slowly drag to slowly go down a list". rohkea's suggestion is well in line with the standards, it's just problematic for R48.

**Comment by 20kdc** [comment]
...for lack of a better solution I'm just going to close this as won't-fix... sorry.
