### ISSUE TITLE
You only see that the text exceeds limit after entering it, on Android

### ISSUE THREAD

**Issue by rohkea** [20kdc/gabien-app-r48#45]
On Android, the remaining character count is not visible until you actually press OK. This makes editing text harder. I **think** it should be possible to add a counter near the text input. At least many applications do something like that.

**Comment by 20kdc** [comment]
It's possible but the text length needs to be handled in R48 terms, not in absolute string length terms, due to the cases that had to be handled for R2k string lengths.

This means a bit of a duet between Android and R48. Doable but I think I'll wait until after the other stuff.

**Comment by 20kdc** [comment]
Fixed, and also improved the general 'feel' of R48 textboxes as well.
There now may be some layout oddities, but at least you now don't have to worry about pressing Back leaving R48 entirely.

**Comment by 20kdc** [comment]
Bug is apparently still around due to Android trying to do the same trick R48 does to free up space in landscape mode... Until I learn of a method to show the information, this'll just have to be left open.

**Comment by 20kdc** [comment]
...pretty sure I got around to resolving this properly (dealt with the Android thing) ages back, re-open if I'm incorrect
