### ISSUE TITLE
Event's custom move routes are broken in the current master

### ISSUE THREAD

**Issue by rohkea** [20kdc/gabien-app-r48#49]
Something is seriously wrong with the move route editing in the current master. At least when I edit move routes in the event's custom move routes.

Here's what I'm creating in R48:
![Set graphics, then turn around](https://user-images.githubusercontent.com/3201243/56455415-bb32e680-6366-11e9-8945-7c6a95558f72.png)

Here's what is actually being created:
![A not of 'Move North' commands between the commands I need](https://user-images.githubusercontent.com/3201243/56455422-c84fd580-6366-11e9-8e5a-34e91b771b89.png)

Looks like unused parameters are being turned into 'Move north' commands, or something like that.

This doesn't seem to happen when I'm editing move routes set via Move Event event command, only with custom move routes.

**Comment by 20kdc** [comment]
Should be covered in master.
