### ISSUE TITLE
Several transparent colours are confusing

### ISSUE THREAD

**Issue by rohkea** [20kdc/gabien-app-r48#51]
It's rarely useful to have several fully-transparent colours with opacity of 0. Yet, R48 makes creating them by accident very easy: when you create a new colour, the transparency of the previous colour is preset as the default, so if you're not careful enough, you'll end up with many transparent colours.

What is worse, when exporting an image with several transparent colours to 8-bit PNG, they are saved in a way that is incompatible with EasyRPG, RPG Maker 2000 and 2003:

![transparent](https://user-images.githubusercontent.com/3201243/56461357-13470880-63ba-11e9-883d-eb0ce8592d42.png)

This would display as follows:
![screenshot_0](https://user-images.githubusercontent.com/3201243/56461360-2659d880-63ba-11e9-88f8-dfec3f47e204.png)

I suggest this: when adding a new colour, and the existing colour has Alpha of 0, then pre-set alpha to 255. (This means people who know what they are doing would still be able to enter 0 manually, but the rest of us won't get confused by several transparent colours.)

**Comment by 20kdc** [comment]
...ah. ...Yeah, the way multiple transparent colours are saved is setup in a way that... *should* be valid PNG-wise but won't play well with the way they're treated by RPG Maker engines.
I should probably setup a warning for saving with the invalid setups...

**Comment by 20kdc** [comment]
Assuming closed for now given I've implemented a slightly modified version of your suggestion in master.
