### ISSUE TITLE
RM2k3 skeleton has problems with RM2k3

### ISSUE THREAD

**Issue by rohkea** [20kdc/gabien-app-r48#52]
The 2003 skeleton project is not 100% compatible with RPG Maker 2003. While it's runnable with RPG_RT (mostly, except PNG format, see below), editor has trouble opening it.

The editor expects animations to have at least one frame:
![skeleton-animations](https://user-images.githubusercontent.com/3201243/56461732-4b514a00-63c0-11e9-98cd-47307efc4c9c.png)

Template tileset format is no longer compatible with RM2k/2k3 since it became greyscale (maybe it has too few colours or something):
![template-tileset-format](https://user-images.githubusercontent.com/3201243/56461800-61133f00-63c1-11e9-86ff-b890d2d67d22.png)

'Troops' page expects that all troops have at least one battle event (with condition of 'none' and no commands in it), otherwise displays an error:
![troops](https://user-images.githubusercontent.com/3201243/56461863-4c837680-63c2-11e9-8da5-788261f70c81.png)
(The error is not fatal. You can click OK, click on 'New Page' and then the error disappears)

Otherwise it seems to work.

**Comment by 20kdc** [comment]
Assuming closed for now given the commit fixing this in master.
