### ISSUE TITLE
Android version freezes when choosing target engine

### ISSUE THREAD

**Issue by Yabuato** [20kdc/gabien-app-r48#53]
My device is Android 5.1.1 and latest version of R48.

**Comment by 20kdc** [comment]
Which engine did you choose?
...Starting up takes a while, particularly if you chose certain target games.
Allow it to continue running for a while - if that doesn't work, I'll need more information.
In the meantime, I'll probably add a second loading screen.

**Comment by Yabuato** [comment]
R2k/3.
It loads fine when choose a RGSS engine.

I did a recording
https://youtu.be/pfv6BvuqcXw

**Comment by 20kdc** [comment]
Mind testing this version? It's based off current master, with a minor change to layertabs.png to make it clear this isn't v1.3-2. It has a more informative loading screen.
https://20kdc.duckdns.org/v1.3-X-Yabuato-Testing.apk

**Comment by rohkea** [comment]
I can't reproduce this error, it loads for me. Ara Fell took some time to load (around 10 seconds, I haven't timed it), but it did load.

I've tested with the latest version of Ara Fell from itch.io and R48 v. 1.3-1. My device is Xiaomi Redmi 6 Pro (M1805D1SE, Octa-core Max 2.0GHz CPU, 4 GB RAM) with Android 8.1.0.

**Comment by Yabuato** [comment]
> Mind testing this version? It's based off current master, with a minor change to layertabs.png to make it clear this isn't v1.3-2. It has a more informative loading screen.
> https://20kdc.duckdns.org/v1.3-X-Yabuato-Testing.apk

It doesn't freeze anymore and can load games fine.
Thanks,this issue is fixed.
