### ISSUE TITLE
NOTICE: Changeover from CC0 to another compatible license

### ISSUE THREAD

**Issue by 20kdc** [20kdc/gabien-app-r48#56]
https://lwn.net/ml/fedora-legal/CAC1cPGw1xScGAXo-0NRs92zFB7ptRxTt=oCYi0BxfZDfAgUtYQ@mail.gmail.com/

Need to pick a license just out of courtesy.
Note to downstream users: Your existing rights and those to future versions will not be affected by this change.
I don't *have* any patents, period, but switching to a license that implicitly grants them (presumably via the first-party doctrine) would be ideal just as accident avoidance.

**Comment by 20kdc** [comment]
For the record, BSD0's the current one I'm thinking of changing to, though MIT0 is on the table.
This change will also affect gabien and therefore by extension Wrench To Forehead.

**Comment by fdelapena** [comment]
Another option is the Unlicense, similar to CC0 (Fedora suggests this one as a closer replacement).

**Comment by 20kdc** [comment]
@fdelapena 
Regarding Unlicense: Good point, good point
...I admit I kind of forgot about this license change plan
(there's a lot of notices to change over, since R48 has a license header on each file)

**Comment by 20kdc** [comment]
@rohkea You're on the contributors list, so I'm checking this with you before I finally commit this: Is it okay to relicense R48 to the Unlicense?

**Comment by rohkea** [comment]
I'm totally OK with changing the license, either to Unlicense or to any other license

**Comment by 20kdc** [comment]
I took a while to get around to this, but on the flip-side that just means notice was given for a long time, so that's probably for the best.
