### ISSUE TITLE
choosing music for map says unable to load sound

### ISSUE THREAD

**Issue by vilo1839** [20kdc/gabien-app-r48#59]
I don't really know what I'm doing but I got this message when trying to set sofafun.mp3 to the music of a map.
![image](https://github.com/20kdc/gabien-app-r48/assets/139687192/b9012ce7-36bf-48be-af15-986b14d2bc2a)
Unable to load sound.

**Comment by 20kdc** [comment]
R48 itself can't load MP3 files. EasyRPG & RPG Maker 2000/2003 can, so it's business as usual.
Though I'm kinda worried as to what appears to have happened with the text rendering here; that could imply a worse bug that probably needs solving.

**Comment by vilo1839** [comment]
Yeah I never remembered it looking like that when I used it a while ago on another thing, I don't really remember.
So if I load the project on easyrpg should the music work then? When I tried that after seeing the "unable to load sound" thingy I didn't hear music within the game (I did have easyrpg music working when loading another game)

**Comment by 20kdc** [comment]
> Yeah I never remembered it looking like that when I used it a while ago on another thing, I don't really remember. So if I load the project on easyrpg should the music work then? When I tried that after seeing the "unable to load sound" thingy I didn't hear music within the game (I did have easyrpg music working when loading another game)

MP3 should work with both EasyRPG and the original runtime. That said testing is always the way to go - the audio preview here is meant to be more like guidance for "which track is this anyway" and pitch.

**Comment by vilo1839** [comment]
> Though I'm kinda worried as to what appears to have happened with the text rendering here; that could imply a worse bug that probably needs solving.

I get this when running ```java -jar v1.5.jar``` so maybe its the font missing part at the bottom?
```
GaBIEn: Successfully set app resource prefixes to: "r48/"
gabien.natives.Loader: gabien-natives/natives.x86_64-linux-gnu -> /tmp/natives.x86_64-linux-gnu16058110172172981405.tmp
GaBIEn: Natives: awakening-songbird
FONT: Font has preloaded
BADGPU: GL Extensions: GL_EXT_debug_label GL_EXT_map_buffer_range GL_EXT_robustness GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_s3tc GL_EXT_texture_format_BGRA8888 GL_KHR_debug GL_EXT_memory_object GL_EXT_memory_object_fd GL_NV_memory_object_sparse GL_EXT_semaphore GL_EXT_semaphore_fd GL_NV_timeline_semaphore GL_NV_memory_attachment GL_NV_texture_compression_s3tc GL_OES_compressed_ETC1_RGB8_texture GL_EXT_compressed_ETC1_RGB8_sub_texture GL_OES_compressed_paletted_texture GL_OES_draw_texture GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_element_index_uint GL_OES_extended_matrix_palette GL_OES_fbo_render_mipmap GL_OES_framebuffer_object GL_OES_matrix_get GL_OES_matrix_palette GL_OES_packed_depth_stencil GL_OES_point_size_array GL_OES_point_sprite GL_OES_rgb8_rgba8 GL_OES_read_format GL_OES_stencil8 GL_OES_texture_cube_map GL_OES_texture_npot GL_OES_vertex_half_float 
./r48/fonts.r48 wasn't found.
```

**Comment by vilo1839** [comment]
> MP3 should work with both EasyRPG and the original runtime. That said testing is always the way to go - the audio preview here is meant to be more like guidance for "which track is this anyway" and pitch.

So there's no music (there's sound) when I use easyrpg on a project I made using r48

https://github.com/20kdc/gabien-app-r48/assets/139687192/820aaa0b-52b1-4672-b331-68768986b474

Then when I open a project I made using rpg maker 2003 there is music (I tried replacing a song in r48 and it still worked) so I'm confused.

https://github.com/20kdc/gabien-app-r48/assets/139687192/846c560a-80cc-419f-89d9-645476567251

I don't really know if I did something or if there's something I can try?

**Comment by 20kdc** [comment]
Ah! It's the music_type field. It's set to "inherit" in the first case, which means the music is inherited from the parent map (if any).

**Comment by vilo1839** [comment]
Thaaanks !!! I didn't notice that, it works now
so is "unable to load sound" just a disclaimer that like... r48 can't load sound for playback? I don't understand that much
