### ISSUE TITLE
Drawing rectangles in any order

### ISSUE THREAD

**Issue by rohkea** [20kdc/gabien-app-r48#6]
Currently, the rectangle is drawn only if you draw it ↘ from top-left corner to the bottom-right.

Other orders don’t work (↖ ↙ ↗), and it would be nice if they did. Or at least if the current behaviour were better documented.

**Comment by 20kdc** [comment]
.The rectangle tool has been generally improved in master now.
It should fix this, and allow tiling larger brushes.

**Comment by rohkea** [comment]
Works great now, thanks!

The only nitpicking I have is that drawing rectangles with an upper-layer tiles, the black background is shown instead of the actual background. But this is OK as it is, it’s just nitpicking. ^^'

**Comment by 20kdc** [comment]
Unsure what to do there.
Right now the code is intended to do this to prevent other layers hiding what you are doing.

**Comment by 20kdc** [comment]
...Haven't heard much regarding this, closing (re-open if there's anything specific to do regarding this)
