### ISSUE TITLE
how could i make an invisible event/ an event using a chipset,, is that possible?

### ISSUE THREAD

**Issue by vilo1839** [20kdc/gabien-app-r48#60]
I want to make an interactive item on the floor but don't want to turn it into a charset, is that possible? 
![image](https://github.com/20kdc/gabien-app-r48/assets/139687192/333c0875-ba30-4860-82b2-072eb76d016f)

**Comment by 20kdc** [comment]
Making an invisible event is possible by simply not providing a charset name in `@character_name`.
You can also make an event using a tile. See "Select Tile Graphic" here.
![image](https://github.com/20kdc/gabien-app-r48/assets/22304167/e1294b98-ad6e-4db5-82f1-b071293ed6f5)

**Comment by vilo1839** [comment]
Oh my gosh! I saw that but thought I had to press the right button for some reason the "Select character index..." nevermind! Thank you. I wonder if I'm like the only person who would ever get that wrong haha, do you have anything for donations by the way?

**Comment by 20kdc** [comment]
I don't. Anyway, I assume by that the issue is resolved, reopen it if I'm wrong?
