### ISSUE TITLE
R48 Editor doesn't get past bootup

### ISSUE THREAD

**Issue by Penncilk** [20kdc/gabien-app-r48#63]
![image](https://github.com/20kdc/gabien-app-r48/assets/26704396/461aa85e-e80e-490e-b67f-8c40d0ec4406)
![image](https://github.com/20kdc/gabien-app-r48/assets/26704396/4ff80ef2-19e5-4754-b405-c14d4c04b4a4)
I'm unsure what the issue is,

**Comment by Penncilk** [comment]
I found out that version 1.4-3 works on my system however,

**Comment by 20kdc** [comment]
Huh! Can you please try `LIBGL_ALWAYS_SOFTWARE=1 java -jar (etc...)` when running R48? I'll admit, I don't understand how this happened, but that might provide an acceptable workaround for the moment. I would also like to see the output of the `eglinfo` command.

**Comment by 20kdc** [comment]
Oh! It's possible you might not have the package `libgles1`.
R48 uses OpenGL ES 1 (and desktop OpenGL 1 on Windows) in order to ensure compatibility with the widest range of hardware possible. However, it appears that expecting all Linux systems to support OpenGL ES 1 may have been a little hasty.

**Comment by Penncilk** [comment]
I installed libgles1, but I still got the same error,
Same with running the app with software rendering

**Comment by 20kdc** [comment]
Alright, I think I'll need the output of `eglinfo` on your system to really make any headway here, sorry!

**Comment by Penncilk** [comment]
No worries! Thank you so much for helping me through this
I hope this helps!
[eglinfo.txt](https://github.com/20kdc/gabien-app-r48/files/14875643/eglinfo.txt)

**Comment by Penncilk** [comment]
It works! Thank you so much! ^^

**Comment by Penncilk** [comment]
It worked when I used the workaround ^^

**Comment by 20kdc** [comment]
Hmm. What GPU are you using? While it's good this worked, it also seems weird?

**Comment by Penncilk** [comment]
I'm using an Integrated Intel UHD Graphics 620! ^^

**Comment by Penncilk** [comment]
Oops, my phone glitched out and deleted a previous comment

**Comment by 20kdc** [comment]
...huh.
Well, in any case, I guess it works now and I'll make a new release? (There's now also a useful message should this happen again to anyone else.)
The comment you deleted was the one with the `eglinfo.txt` results; if you don't mind I can reupload them for future reference?

**Comment by 20kdc** [comment]
Closing for now, though this might come up again later, hmm.

**Comment by Penncilk** [comment]
Oh! I don't mind ^^ sure thing!

**Comment by 20kdc** [comment]
[eglinfo.txt](https://github.com/20kdc/gabien-app-r48/files/14891301/eglinfo.txt)
attached `eglinfo` results for the device in question

**Comment by 20kdc** [comment]
An update on this: I forgot `eglBindAPI` and later versions of Ubuntu don't ship an OpenGL ES 1 implementation. There was supposed to be a fallback path to use desktop OpenGL, but, well, again, I forgot `eglBindAPI`.

**Comment by 20kdc** [comment]
@roxwize I might have forgotten to ship a bugfix update?
Please see if the following JAR works (built off of latest code).

[roxwize-test.zip](https://github.com/user-attachments/files/18737133/roxwize-test.zip)

**Comment by 20kdc** [comment]
@roxwize Can I get ahold of the error you're having without `BADGPU_EGL_LIBRARY`?

**Comment by 20kdc** [comment]
@roxwize since your distribution appears to be missing key libraries (either of: `libEGL.so` / `libEGL.so.1`) as part of the desktop distribution, I think it's reasonable for me to consider it "outside of the support gamut".
I'm not even sure your distribution could run Wayland programs in this; not that I consider Wayland good per-se, but not even having the libraries to run them properly installed is, IMO, a bad sign.
I'm happy to see that the ANGLE workaround works for you at least.

**Comment by 20kdc** [comment]
@roxwize You can use precompiled natives. I know the native build instructions are a lot; this was an unfortunate but necessary sacrifice.
The use of two specific versions of the Android NDK was to maximize compatibility from the oldest to the newest Android devices.
