### ISSUE TITLE
Passability Overlay has left and right reversed

### ISSUE THREAD

**Issue by zaidalkaz** [20kdc/gabien-app-r48#64]
Changing a tiles passability to "down" correctly shows that the tile is passable from below (the "down" arrows are removed).
This applies to "up" as well.
However for whatever reason left and right are switched in the overlay, with tiles passable from the left having their right arrows removed and vice versa.
You can test this easily by placing a solid tile on the map then changing its passability in tileset settings while the passability overlay is on.

**Comment by zaidalkaz** [comment]
Should probably add to this that I'm using v2.0-rc2, the latest release

**Comment by 20kdc** [comment]
...ah, thank you! Found and fixed. Seeing as there's been various other changes since that release, I'll issue a new RC shortly, and will close then.

**Comment by 20kdc** [comment]
https://github.com/20kdc/gabien-app-r48/releases/tag/v2.0-rc3
