### ISSUE TITLE
Visual indication for overflowing text in property values

### ISSUE THREAD

**Issue by rohkea** [20kdc/gabien-app-r48#8]
Many properties in RM2k[3] have a length limit, and going beyond that limit will make part of the string ignored in the Player. It would be nice to add those limits.

The list below is incomplete, I plan to edit this message in the future. The values are obtained from the official RM2k and are believed to correspond to EasyRPG values (but might be wrong for the pirated versions because of the 1/4-width space sign there):

* `RPG_RT.ldb` → `@actors{N}` → `@name` has a limit of 12 half-width characters (or 6 full-width characters),
* `RPG_RT.ldb` → `@actors{N}` → `@title` has a limit of 12 half-width characters (or 6 full-width characters),
* `RPG_RT.ldb` → `@skills{N}` → `@name` has a limit of 20 half-width characters (or 10 full-width characters),
* `RPG_RT.ldb` → `@skills{N}` → `@description` has a limit of 50 half-width characters (or 25 full-width characters),
* `RPG_RT.ldb` → `@items{N}` → `@name` has a limit of 20 half-width characters (or 10 full-width characters),
* `RPG_RT.ldb` → `@items{N}` → `@description` has a limit of 50 half-width characters (or 25 full-width characters),
* `RPG_RT.ldb` → `@enemies{N}` → `@name` has a limit of 20 half-width characters (or 10 full-width characters),
* `RPG_RT.ldb` → `@states{N}` → `@name` has a limit of 8 half-width characters (or 4 full-width characters),
* RPG_RT.ldb → `@terms` →  `shop1Greet`, `shop1Impatient`, `shop1Buy`, `shop1Sell`, `shop1Leave`, `shop1WTBQuestion`, `shop1IoBQuestion`, `shop1Done`, `show1WTSQuestion`, `shop1ICoSQuestion`, `shop1Thanks` (same for shop2, shop3) — 50 chars,
* RPG_RT.ldb → `@terms` → `inn1PriceX` — 50 chars in 2k v.1.61 [TODO: Japanese/pirated?]
* RPG_RT.ldb → `@terms` → `inn1XGoldToSleep` — not used in 2k v.1.61 [TODO: Japanese/pirated?]
* [to be continued],

I will update this list with the limits for skill usage, state messages and game vocabulary later.

### Strings that are word-wrapped in v.1.61 but have limits in older versions

The official English RPG Maker 2000 v.1.61 introduced word-wrapping, so the text that used to be limited (because they needed to fit the line) no longer need to be limited in that version. However, they were limited in previous versions. I’m not sure if something needs to be done about them. All of them do have a limit of 100 in RM2k editor, but it seems arbitrary:

* RPG_RT.ldb → `@skills{N}` → `@use_text_1_2KO`,
* RPG_RT.ldb → `@skills{N}` → `@use_text_2_2KO`,
* RPG_RT.ldb → `@states{N}` → `@msg_actor`,
* RPG_RT.ldb → `@states{N}` → `@msg_enemy`,
* RPG_RT.ldb → `@states{N}` → `@msg_recovery`,
* RPG_RT.ldb → `@terms` → `annXEncounter`, `preemptiveAttack`, `ranAwaySafely`, `failedToEscape`, `wonACombat`, `partyDead`, `experience`, `youFound`, `xReceived`, `annXAttacksTheEnemy2KO`, `annCritEnemyHurt2KO`, `annXGuarding2KO`, `annXDoesNothing2KO`, `annXReadies2Attacks2KO`, `annXSelfDestructs2KO`, `annXRunsAway2KO`, `annXTransforms2KO`, `annEHurtForXHP2KO`, `annXMissedE2KO`, `annPHurtForXHP2KO`, `annXMissedP2KO`, `annXFloppedSkillA2KO`, `annXFloppedSkillB2KO`, `annXFloppedSkillC2KO`, `annXDodged2KO`, `annUsedItem2KO`, `paramInt2KO`, `paramDec2KO`, `annXHPAbsorbedFromE2KO`, `annXHPAbsorbedFromP2KO`, `resistInc2KO`, `resistDec2KO`, `levelUp`, `annLearnedX`, [to be continued].

In Japanese versions, pirated versions and the official RM2k v.1.60, those strings have different limits.

For more info on fullwidth characters, see #7.

**Comment by 20kdc** [comment]
Both this & #7 are basically the same issue (resolvable by creating a subclass/replacement for StringSchemaElement & using it where needed), but it's a matter of how the UI on that should work - if it should be attempted - given R48's attempt at handling at least "more languages than RPG Maker 2000/2003", though nothing with special layout rules.
The result certainly can't be a hard limit...

**Comment by rohkea** [comment]
> working 'support' (or to be more precise, lack of getting in the OS's way) for some language with a lot of reliance on ligatures

Currently, EasyRPG uses a built-in bitmap font with no support for ligatures.

Support for arbitrary TTF fonts via HarfBuzz is planned, and then we probably can check the size based on pixels, but this will be a non-default option. The bitmap font will probably remain the default (because compatibility), so it needs to be handled in any case.

**Comment by 20kdc** [comment]
Hopefully fixed now, do test.
