### ISSUE TITLE
When brush is >1 tile, only 1 tile is shown when hovering over the map

### ISSUE THREAD

**Issue by rohkea** [20kdc/gabien-app-r48#9]
This is not very intuitive: when I first encountered this behaviour, I thought I can’t use brushes >1 tile in R48.

**Comment by 20kdc** [comment]
I'm actually pretty sure this is fixed in master by now, but do check first.

**Comment by rohkea** [comment]
Just tested this, it works like a charm now, thanks!

**Comment by 20kdc** [comment]
Close as it apparently works.
